apiVersion: v1
kind: Secret
metadata:
  name: market-data-secrets
  namespace: market-data
type: Opaque
stringData:
  POSTGRES_PASSWORD: "***************"
  DATABASE_URL: "postgresql://postgres:***************@postgres:5432/stocks_db"